//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auction_portal.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tb_user
    {
        public int ID { get; set; }
        [Required(ErrorMessage="** fill the field")]
        public string Name { get; set; }
        [Required(ErrorMessage = "* fill the field")]
        public Nullable<double> Price { get; set; }
        [Required(ErrorMessage = "* fill the field")]
        public string Description { get; set; }
        [Required(ErrorMessage = "* fill the field")]
        public Nullable<int> Mobile { get; set; }
        [Required(ErrorMessage = "* fill the field")]
        public string Address { get; set; }
        [Required(ErrorMessage = "* fill the field")]
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public tb_user()
        {
            ImagePath = "~/AppFiles/Images/Rizwan.png";
        }
    }
}
